name: "Unit Testing"

on: [pull_request]

jobs:
  Static:
    name: "Static checks, Node Version ${{ matrix.node_version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 16
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Cache Node
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      
      - name: Run static
        run: |
          npm install
          npm run lint
      
      - name: Run unit testing
        run: |
          npm run test:unit:ci
